<?php

namespace Database\Seeders;

use App\Models\JobListing;
use App\Models\JobSkill;
use Illuminate\Database\Seeder;

class JobListingSeeder extends Seeder
{
    public function run(): void
    {
        \Illuminate\Support\Facades\DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        JobSkill::truncate();
        JobListing::truncate();
        \Illuminate\Support\Facades\DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        $jobs = [
            // ── Teknologi ──
            [
                'title' => 'Frontend Developer (React)',
                'company_name' => 'Tokopedia',
                'location' => 'Jakarta',
                'job_type' => 'full-time',
                'level' => 'mid',
                'category' => 'Teknologi',
                'description' => 'Bergabunglah dengan tim frontend Tokopedia untuk membangun pengalaman belanja terbaik bagi jutaan pengguna. Anda akan bekerja dengan React, TypeScript, dan sistem desain internal kami.',
                'requirements' => "- Pengalaman 2+ tahun dengan React.js\n- Menguasai TypeScript dan CSS/SCSS\n- Familiar dengan REST API dan GraphQL\n- Pengalaman dengan unit testing (Jest/RTL)",
                'salary_min' => '12.000.000',
                'salary_max' => '22.000.000',
                'salary_visible' => true,
                'deadline' => now()->addDays(30)->toDateString(),
                'apply_url' => 'https://www.tokopedia.com/careers',
                'skills' => ['React.js', 'TypeScript', 'CSS', 'Git', 'GraphQL'],
            ],
            [
                'title' => 'Backend Engineer (Go)',
                'company_name' => 'Gojek',
                'location' => 'Jakarta',
                'job_type' => 'full-time',
                'level' => 'mid',
                'category' => 'Teknologi',
                'description' => 'Bangun layanan backend yang scalable untuk platform super app Gojek. Anda akan mendesain microservices, mengoptimalkan performa, dan berkolaborasi dengan tim product.',
                'requirements' => "- Pengalaman 3+ tahun backend development\n- Menguasai Golang atau Python\n- Memahami distributed systems dan microservices\n- Familiar dengan Kubernetes dan Docker",
                'salary_min' => '18.000.000',
                'salary_max' => '35.000.000',
                'salary_visible' => true,
                'deadline' => now()->addDays(25)->toDateString(),
                'apply_url' => 'https://www.gojek.com/en-id/careers/',
                'skills' => ['Go', 'Python', 'Docker', 'Kubernetes', 'MySQL'],
            ],
            [
                'title' => 'Backend Engineer (Laravel)',
                'company_name' => 'Traveloka',
                'location' => 'Jakarta',
                'job_type' => 'full-time',
                'level' => 'mid',
                'category' => 'Teknologi',
                'description' => 'Kembangkan sistem backend yang mendukung platform perjalanan terbesar di Asia Tenggara. Tangani jutaan transaksi per hari dengan arsitektur yang andal.',
                'requirements' => "- Pengalaman 2+ tahun dengan Laravel\n- Menguasai MySQL dan Redis\n- Memahami arsitektur microservices\n- Pengalaman dengan message queue (RabbitMQ/Kafka)",
                'salary_min' => '15.000.000',
                'salary_max' => '28.000.000',
                'salary_visible' => true,
                'deadline' => now()->addDays(28)->toDateString(),
                'apply_url' => 'https://www.traveloka.com/en-id/career',
                'skills' => ['Laravel', 'PHP', 'MySQL', 'Redis', 'Docker'],
            ],
            [
                'title' => 'Mobile Developer (Flutter)',
                'company_name' => 'Dana Indonesia',
                'location' => 'Jakarta',
                'job_type' => 'full-time',
                'level' => 'mid',
                'category' => 'Teknologi',
                'description' => 'Kembangkan aplikasi dompet digital DANA yang digunakan lebih dari 140 juta pengguna. Buat pengalaman pembayaran yang seamless dan aman.',
                'requirements' => "- Pengalaman 2+ tahun dengan Flutter/Dart\n- Familiar dengan BLoC/Provider/Riverpod\n- Menguasai integrasi REST API\n- Memahami keamanan aplikasi mobile",
                'salary_min' => null,
                'salary_max' => null,
                'salary_visible' => false,
                'deadline' => now()->addDays(21)->toDateString(),
                'apply_url' => 'https://dana.id/careers',
                'skills' => ['Flutter', 'Dart', 'REST API', 'Git', 'Firebase'],
            ],
            [
                'title' => 'Full Stack Developer',
                'company_name' => 'Bukalapak',
                'location' => 'Bandung',
                'job_type' => 'full-time',
                'level' => 'mid',
                'category' => 'Teknologi',
                'description' => 'Bergabung dengan tim engineering Bukalapak untuk membangun fitur-fitur baru marketplace B2B dan B2C. Anda akan bekerja di seluruh stack dari frontend hingga backend.',
                'requirements' => "- Pengalaman 2+ tahun full stack development\n- Menguasai Vue.js atau React dan Node.js\n- Familiar dengan PostgreSQL dan MongoDB\n- Memahami CI/CD pipeline",
                'salary_min' => '14.000.000',
                'salary_max' => '25.000.000',
                'salary_visible' => true,
                'deadline' => now()->addDays(35)->toDateString(),
                'apply_url' => 'https://careers.bukalapak.com/',
                'skills' => ['Vue.js', 'Node.js', 'PostgreSQL', 'Docker', 'Git'],
            ],
            [
                'title' => 'Cloud Engineer',
                'company_name' => 'Telkom Indonesia',
                'location' => 'Bandung',
                'job_type' => 'full-time',
                'level' => 'senior',
                'category' => 'Infrastruktur',
                'description' => 'Kelola dan kembangkan infrastruktur cloud Telkom untuk mendukung layanan digital jutaan pelanggan Indonesia.',
                'requirements' => "- Pengalaman 5+ tahun di cloud computing\n- Sertifikasi AWS/GCP/Azure\n- Menguasai Terraform dan Ansible\n- Familiar dengan Kubernetes",
                'salary_min' => '25.000.000',
                'salary_max' => '45.000.000',
                'salary_visible' => true,
                'deadline' => now()->addDays(40)->toDateString(),
                'apply_url' => 'https://careers.telkom.co.id/',
                'skills' => ['AWS', 'Kubernetes', 'Terraform', 'Docker', 'Linux'],
            ],
            [
                'title' => 'Software Engineer Intern',
                'company_name' => 'Shopee Indonesia',
                'location' => 'Jakarta',
                'job_type' => 'internship',
                'level' => 'entry',
                'category' => 'Teknologi',
                'description' => 'Program magang intensif 6 bulan di Shopee. Terlibat langsung dalam pengembangan fitur platform e-commerce terbesar di Asia Tenggara.',
                'requirements' => "- Mahasiswa aktif S1 semester 5+\n- Menguasai minimal 1 bahasa pemrograman\n- Familiar dengan struktur data dan algoritma\n- Bersedia WFO di Jakarta",
                'salary_min' => '3.000.000',
                'salary_max' => '5.000.000',
                'salary_visible' => true,
                'deadline' => now()->addDays(14)->toDateString(),
                'apply_url' => 'https://careers.shopee.co.id/',
                'skills' => ['Java', 'Python', 'SQL', 'Git'],
            ],
            [
                'title' => 'Android Developer',
                'company_name' => 'Bank BCA',
                'location' => 'Jakarta',
                'job_type' => 'full-time',
                'level' => 'mid',
                'category' => 'Teknologi',
                'description' => 'Kembangkan aplikasi mobile banking BCA yang digunakan jutaan nasabah. Fokus pada keamanan, performa, dan pengalaman pengguna terbaik.',
                'requirements' => "- Pengalaman 3+ tahun Android development (Kotlin)\n- Memahami arsitektur MVVM dan Clean Architecture\n- Familiar dengan keamanan aplikasi banking\n- Pengalaman dengan Jetpack Compose",
                'salary_min' => '15.000.000',
                'salary_max' => '30.000.000',
                'salary_visible' => true,
                'deadline' => now()->addDays(20)->toDateString(),
                'apply_url' => 'https://karir.bca.co.id/',
                'skills' => ['Kotlin', 'Android', 'MVVM', 'REST API', 'Git'],
            ],
            // ── Data & Analytics ──
            [
                'title' => 'Data Analyst',
                'company_name' => 'Gojek',
                'location' => 'Jakarta',
                'job_type' => 'full-time',
                'level' => 'entry',
                'category' => 'Data & Analytics',
                'description' => 'Analisis data dari berbagai layanan Gojek untuk menghasilkan insight bisnis yang actionable. Bantu tim produk membuat keputusan berbasis data.',
                'requirements' => "- Fresh graduate S1 Statistik, Matematika, atau Informatika\n- Menguasai SQL dan Python/R\n- Familiar dengan Tableau atau Looker\n- Kemampuan storytelling data yang baik",
                'salary_min' => '8.000.000',
                'salary_max' => '15.000.000',
                'salary_visible' => true,
                'deadline' => now()->addDays(20)->toDateString(),
                'apply_url' => 'https://www.gojek.com/en-id/careers/',
                'skills' => ['SQL', 'Python', 'Excel', 'Tableau', 'Statistics'],
            ],
            [
                'title' => 'Data Scientist',
                'company_name' => 'Tokopedia',
                'location' => 'Jakarta',
                'job_type' => 'full-time',
                'level' => 'mid',
                'category' => 'Data & Analytics',
                'description' => 'Bangun model machine learning untuk meningkatkan rekomendasi produk, deteksi fraud, dan personalisasi pengalaman belanja 100+ juta pengguna Tokopedia.',
                'requirements' => "- Pengalaman 2+ tahun sebagai Data Scientist\n- Menguasai Python dan scikit-learn/TensorFlow\n- Familiar dengan big data (Spark, Hadoop)\n- Memahami A/B testing",
                'salary_min' => '18.000.000',
                'salary_max' => '35.000.000',
                'salary_visible' => true,
                'deadline' => now()->addDays(30)->toDateString(),
                'apply_url' => 'https://www.tokopedia.com/careers',
                'skills' => ['Python', 'Machine Learning', 'SQL', 'TensorFlow', 'Statistics'],
            ],
            [
                'title' => 'Business Intelligence Analyst',
                'company_name' => 'Bank Mandiri',
                'location' => 'Jakarta',
                'job_type' => 'full-time',
                'level' => 'mid',
                'category' => 'Data & Analytics',
                'description' => 'Analisis performa bisnis Bank Mandiri menggunakan data warehouse dan business intelligence tools untuk mendukung pengambilan keputusan strategis.',
                'requirements' => "- Pengalaman 2+ tahun di BI/Analytics\n- Menguasai SQL dan Power BI/Tableau\n- Familiar dengan data warehouse (Snowflake/BigQuery)\n- Pemahaman produk perbankan",
                'salary_min' => '12.000.000',
                'salary_max' => '22.000.000',
                'salary_visible' => true,
                'deadline' => now()->addDays(25)->toDateString(),
                'apply_url' => 'https://karir.bankmandiri.co.id/',
                'skills' => ['SQL', 'Power BI', 'Excel', 'Python', 'Data Visualization'],
            ],
            // ── Desain ──
            [
                'title' => 'UI/UX Designer',
                'company_name' => 'Shopee Indonesia',
                'location' => 'Jakarta',
                'job_type' => 'full-time',
                'level' => 'entry',
                'category' => 'Desain',
                'description' => 'Rancang pengalaman belanja yang intuitif untuk jutaan pengguna Shopee. Bekerja sama dengan tim produk dan engineering untuk mewujudkan desain yang berdampak.',
                'requirements' => "- Portfolio desain yang kuat\n- Menguasai Figma dan Prototyping\n- Memahami user research\n- Familiar dengan usability testing",
                'salary_min' => '8.000.000',
                'salary_max' => '15.000.000',
                'salary_visible' => true,
                'deadline' => now()->addDays(18)->toDateString(),
                'apply_url' => 'https://careers.shopee.co.id/',
                'skills' => ['Figma', 'Prototyping', 'User Research', 'Adobe XD'],
            ],
            [
                'title' => 'Product Designer',
                'company_name' => 'Traveloka',
                'location' => 'Jakarta',
                'job_type' => 'full-time',
                'level' => 'mid',
                'category' => 'Desain',
                'description' => 'Desain pengalaman perjalanan end-to-end di platform Traveloka. Dari flight booking hingga hotel, Anda bertanggung jawab atas desain yang clean dan fungsional.',
                'requirements' => "- Pengalaman 3+ tahun sebagai Product/UX Designer\n- Portfolio produk digital yang kuat\n- Menguasai Figma dan design system\n- Kemampuan riset pengguna yang baik",
                'salary_min' => '14.000.000',
                'salary_max' => '25.000.000',
                'salary_visible' => true,
                'deadline' => now()->addDays(22)->toDateString(),
                'apply_url' => 'https://www.traveloka.com/en-id/career',
                'skills' => ['Figma', 'Design System', 'User Research', 'Prototyping', 'Sketch'],
            ],
            // ── Marketing ──
            [
                'title' => 'Digital Marketing Specialist',
                'company_name' => 'Bukalapak',
                'location' => 'Jakarta',
                'job_type' => 'full-time',
                'level' => 'mid',
                'category' => 'Marketing',
                'description' => 'Kelola kampanye digital marketing Bukalapak di berbagai channel untuk meningkatkan brand awareness, akuisisi pengguna, dan konversi.',
                'requirements' => "- Pengalaman 2+ tahun di digital marketing\n- Menguasai Google Ads dan Meta Ads\n- Familiar dengan SEO/SEM\n- Kemampuan analisis data marketing",
                'salary_min' => '10.000.000',
                'salary_max' => '18.000.000',
                'salary_visible' => true,
                'deadline' => now()->addDays(28)->toDateString(),
                'apply_url' => 'https://careers.bukalapak.com/',
                'skills' => ['Google Ads', 'Meta Ads', 'SEO', 'Analytics', 'Content Marketing'],
            ],
            [
                'title' => 'Social Media Manager',
                'company_name' => 'Pertamina',
                'location' => 'Jakarta',
                'job_type' => 'full-time',
                'level' => 'mid',
                'category' => 'Marketing',
                'description' => 'Kelola seluruh platform media sosial Pertamina. Buat konten kreatif, kelola komunitas, dan tingkatkan engagement dengan strategi yang tepat.',
                'requirements' => "- Pengalaman 2+ tahun sebagai Social Media Manager\n- Menguasai pembuatan konten visual dan copywriting\n- Familiar dengan tools analitik media sosial\n- Memiliki sense of design yang baik",
                'salary_min' => '8.000.000',
                'salary_max' => '15.000.000',
                'salary_visible' => true,
                'deadline' => now()->addDays(20)->toDateString(),
                'apply_url' => 'https://recruitment.pertamina.com/',
                'skills' => ['Content Creation', 'Copywriting', 'Canva', 'Analytics', 'Community Management'],
            ],
            [
                'title' => 'Content Writer',
                'company_name' => 'Kompas.com',
                'location' => 'Jakarta',
                'job_type' => 'full-time',
                'level' => 'entry',
                'category' => 'Marketing',
                'description' => 'Tulis konten berkualitas tinggi untuk platform berita digital terbesar di Indonesia. Liputan teknologi, bisnis, dan gaya hidup.',
                'requirements' => "- Fresh graduate atau pengalaman 1+ tahun\n- Kemampuan menulis yang baik dalam Bahasa Indonesia\n- Memahami SEO dasar\n- Tertarik dengan dunia digital dan teknologi",
                'salary_min' => '5.000.000',
                'salary_max' => '9.000.000',
                'salary_visible' => true,
                'deadline' => now()->addDays(15)->toDateString(),
                'apply_url' => 'https://www.kompas.com/karir',
                'skills' => ['Menulis', 'SEO', 'WordPress', 'Riset', 'Editing'],
            ],
            // ── Keuangan ──
            [
                'title' => 'Financial Analyst',
                'company_name' => 'Bank BRI',
                'location' => 'Jakarta',
                'job_type' => 'full-time',
                'level' => 'entry',
                'category' => 'Keuangan',
                'description' => 'Analisis keuangan untuk mendukung keputusan bisnis Bank BRI. Buat laporan, model keuangan, dan rekomendasi strategis.',
                'requirements' => "- S1 Akuntansi, Keuangan, atau Manajemen\n- Menguasai Excel dan financial modeling\n- Familiar dengan laporan keuangan\n- Memiliki sertifikasi CFA menjadi nilai plus",
                'salary_min' => '7.000.000',
                'salary_max' => '13.000.000',
                'salary_visible' => true,
                'deadline' => now()->addDays(22)->toDateString(),
                'apply_url' => 'https://e-recruitment.bri.co.id/',
                'skills' => ['Excel', 'Financial Modeling', 'Accounting', 'SQL', 'Power BI'],
            ],
            [
                'title' => 'Investment Analyst',
                'company_name' => 'Astra International',
                'location' => 'Jakarta',
                'job_type' => 'full-time',
                'level' => 'mid',
                'category' => 'Keuangan',
                'description' => 'Analisis peluang investasi dan M&A untuk grup Astra. Evaluasi kelayakan bisnis baru dan portofolio investasi yang ada.',
                'requirements' => "- S1/S2 Keuangan, Ekonomi, atau Manajemen\n- Pengalaman 2+ tahun di investment banking atau konsultansi\n- Menguasai financial modeling dan valuation\n- Kemampuan presentasi yang sangat baik",
                'salary_min' => null,
                'salary_max' => null,
                'salary_visible' => false,
                'deadline' => now()->addDays(30)->toDateString(),
                'apply_url' => 'https://www.astra.co.id/Career',
                'skills' => ['Financial Modeling', 'Valuation', 'Excel', 'PowerPoint', 'M&A'],
            ],
            // ── Product ──
            [
                'title' => 'Product Manager',
                'company_name' => 'Tokopedia',
                'location' => 'Jakarta',
                'job_type' => 'full-time',
                'level' => 'mid',
                'category' => 'Produk',
                'description' => 'Pimpin pengembangan fitur-fitur strategis Tokopedia. Definisikan roadmap produk, bekerja dengan engineering dan desain, serta ukur dampak dengan data.',
                'requirements' => "- Pengalaman 3+ tahun sebagai Product Manager\n- Kemampuan analisis data yang kuat\n- Pengalaman bekerja dengan tim engineering\n- Menguasai SQL dan product analytics",
                'salary_min' => '20.000.000',
                'salary_max' => '40.000.000',
                'salary_visible' => true,
                'deadline' => now()->addDays(25)->toDateString(),
                'apply_url' => 'https://www.tokopedia.com/careers',
                'skills' => ['Product Strategy', 'SQL', 'Analytics', 'Agile', 'Figma'],
            ],
            [
                'title' => 'Product Manager (Fintech)',
                'company_name' => 'OVO',
                'location' => 'Jakarta',
                'job_type' => 'full-time',
                'level' => 'mid',
                'category' => 'Produk',
                'description' => 'Pimpin pengembangan produk pembayaran digital OVO. Fokus pada peningkatan conversion rate, retensi pengguna, dan pengembangan fitur baru.',
                'requirements' => "- Pengalaman 3+ tahun sebagai PM di fintech/startup\n- Menguasai product analytics\n- Familiar dengan regulasi fintech Indonesia\n- Kemampuan stakeholder management yang baik",
                'salary_min' => '22.000.000',
                'salary_max' => '38.000.000',
                'salary_visible' => true,
                'deadline' => now()->addDays(18)->toDateString(),
                'apply_url' => 'https://www.ovo.id/careers',
                'skills' => ['Product Management', 'Analytics', 'SQL', 'Figma', 'Agile'],
            ],
            // ── HR & Umum ──
            [
                'title' => 'HR Talent Acquisition',
                'company_name' => 'Gojek',
                'location' => 'Jakarta',
                'job_type' => 'full-time',
                'level' => 'entry',
                'category' => 'Human Resources',
                'description' => 'Rekrut talenta terbaik untuk bergabung dengan tim Gojek. Kelola proses rekrutmen end-to-end dan bangun employer branding yang kuat.',
                'requirements' => "- S1 Psikologi, Manajemen SDM, atau bidang terkait\n- Pengalaman 1+ tahun di rekrutmen\n- Familiar dengan LinkedIn Recruiter\n- Kemampuan komunikasi dan negosiasi yang baik",
                'salary_min' => '7.000.000',
                'salary_max' => '12.000.000',
                'salary_visible' => true,
                'deadline' => now()->addDays(20)->toDateString(),
                'apply_url' => 'https://www.gojek.com/en-id/careers/',
                'skills' => ['Rekrutmen', 'LinkedIn', 'Komunikasi', 'MS Office', 'HR Tools'],
            ],
            [
                'title' => 'Business Development Executive',
                'company_name' => 'Traveloka',
                'location' => 'Jakarta',
                'job_type' => 'full-time',
                'level' => 'entry',
                'category' => 'Bisnis',
                'description' => 'Kembangkan kemitraan strategis Traveloka dengan hotel, maskapai, dan penyedia layanan perjalanan lainnya di Indonesia dan Asia Tenggara.',
                'requirements' => "- S1 semua jurusan\n- Kemampuan negosiasi dan presentasi yang baik\n- Familiar dengan industri travel atau hospitality\n- Bersedia melakukan perjalanan bisnis",
                'salary_min' => '7.000.000',
                'salary_max' => '13.000.000',
                'salary_visible' => true,
                'deadline' => now()->addDays(25)->toDateString(),
                'apply_url' => 'https://www.traveloka.com/en-id/career',
                'skills' => ['Negosiasi', 'Presentasi', 'Excel', 'CRM', 'Komunikasi'],
            ],
            [
                'title' => 'Customer Success Manager',
                'company_name' => 'Salesforce Indonesia',
                'location' => 'Jakarta',
                'job_type' => 'full-time',
                'level' => 'mid',
                'category' => 'Bisnis',
                'description' => 'Pastikan kepuasan dan kesuksesan klien enterprise Salesforce di Indonesia. Bantu adopsi produk, tingkatkan penggunaan, dan perpanjang kontrak.',
                'requirements' => "- Pengalaman 3+ tahun di customer success atau account management\n- Familiar dengan produk Salesforce atau CRM lain\n- Kemampuan presentasi enterprise yang kuat\n- Bahasa Inggris aktif",
                'salary_min' => null,
                'salary_max' => null,
                'salary_visible' => false,
                'deadline' => now()->addDays(30)->toDateString(),
                'apply_url' => 'https://www.salesforce.com/company/careers/',
                'skills' => ['CRM', 'Salesforce', 'Account Management', 'Presentasi', 'English'],
            ],
            // ── Magang / Entry Level ──
            [
                'title' => 'Fullstack Developer Intern',
                'company_name' => 'Pertamina Digital',
                'location' => 'Jakarta',
                'job_type' => 'internship',
                'level' => 'entry',
                'category' => 'Teknologi',
                'description' => 'Program magang 3 bulan di divisi digital Pertamina. Bantu pengembangan aplikasi internal dan digital services untuk operasional energi nasional.',
                'requirements' => "- Mahasiswa aktif semester 5+\n- Menguasai HTML, CSS, JavaScript\n- Memahami dasar-dasar backend (Node.js / PHP / Python)\n- Bersedia WFO Jakarta",
                'salary_min' => '2.000.000',
                'salary_max' => '3.500.000',
                'salary_visible' => true,
                'deadline' => now()->addDays(12)->toDateString(),
                'apply_url' => 'https://recruitment.pertamina.com/',
                'skills' => ['JavaScript', 'HTML', 'CSS', 'PHP', 'Git'],
            ],
            [
                'title' => 'Data Engineering Intern',
                'company_name' => 'Bank BCA',
                'location' => 'Jakarta',
                'job_type' => 'internship',
                'level' => 'entry',
                'category' => 'Data & Analytics',
                'description' => 'Bergabung dengan tim data engineering BCA untuk membantu pengelolaan data pipeline, ETL process, dan infrastruktur data warehouse.',
                'requirements' => "- Mahasiswa aktif S1 Informatika, Statistik, atau Matematika\n- Familiar dengan SQL dan Python\n- Memahami konsep database dasar\n- Nilai akademik minimal 3.0",
                'salary_min' => '2.500.000',
                'salary_max' => '4.000.000',
                'salary_visible' => true,
                'deadline' => now()->addDays(15)->toDateString(),
                'apply_url' => 'https://karir.bca.co.id/',
                'skills' => ['SQL', 'Python', 'ETL', 'Excel', 'Statistics'],
            ],
            [
                'title' => 'UI/UX Design Intern',
                'company_name' => 'Grab Indonesia',
                'location' => 'Jakarta',
                'job_type' => 'internship',
                'level' => 'entry',
                'category' => 'Desain',
                'description' => 'Magang di tim design Grab untuk membantu pengembangan pengalaman pengguna aplikasi ride-hailing, food delivery, dan financial services.',
                'requirements' => "- Mahasiswa aktif jurusan Desain, DKV, atau Informatika\n- Menguasai Figma\n- Memiliki portfolio desain UI/UX\n- Passion di bidang mobile app design",
                'salary_min' => '2.500.000',
                'salary_max' => '4.000.000',
                'salary_visible' => true,
                'deadline' => now()->addDays(10)->toDateString(),
                'apply_url' => 'https://grab.careers/',
                'skills' => ['Figma', 'UI Design', 'UX Research', 'Prototyping'],
            ],
            [
                'title' => 'Software Engineer (Remote)',
                'company_name' => 'Kalibrr',
                'location' => 'Remote',
                'job_type' => 'remote',
                'level' => 'entry',
                'category' => 'Teknologi',
                'description' => 'Bergabung dengan tim engineering Kalibrr secara remote. Bangun platform rekrutmen yang menghubungkan jutaan pencari kerja dengan perusahaan terbaik.',
                'requirements' => "- Fresh graduate atau pengalaman 1+ tahun\n- Menguasai JavaScript (React/Node.js)\n- Comfortable bekerja remote dan async\n- Kemampuan self-management yang baik",
                'salary_min' => '8.000.000',
                'salary_max' => '15.000.000',
                'salary_visible' => true,
                'deadline' => now()->addDays(30)->toDateString(),
                'apply_url' => 'https://www.kalibrr.com/en-US/code-of-conduct',
                'skills' => ['JavaScript', 'React.js', 'Node.js', 'Git', 'REST API'],
            ],
        ];

        foreach ($jobs as $jobData) {
            $skills = $jobData['skills'];
            unset($jobData['skills']);
            $job = JobListing::create($jobData);
            foreach ($skills as $skill) {
                JobSkill::create(['job_listing_id' => $job->id, 'skill_name' => $skill]);
            }
        }
    }
}
